<h2>Listing <span class='muted'>Stocks</span></h2>
<br />
<?php if ($stocks): ?>
    <table class="table table-striped">
        <thead>
    	<tr>
    	    <th>Name</th>
    	    <th>Stock Group</th>
    	    <th>qty</th>
    	    <th>&nbsp;</th>
    	</tr>
        </thead>
        <tbody>
	    <?php foreach ($stocks as $item): ?>		
		<tr>
		    <td><?php echo $item->name; ?></td>
		    <td><?php echo $item->stockgroup->name; ?></td>
		    <td><?php echo $item->qty; ?></td>
		    <td>
			<div class="btn-toolbar">
			    <div class="btn-group">
				<?php echo Html::anchor('stocks/view/' . $item->id, '<i class="icon-eye-open"></i> View', array('class' => 'btn btn-small')); ?>
				<?php if ($auth_instance->member(50) || $auth_instance->member(100)) : ?>
				<?php echo Html::anchor('stocks/edit/' . $item->id, '<i class="icon-wrench"></i> Edit', array('class' => 'btn btn-small')); ?>						
				<?php echo Html::anchor('stocks/delete/' . $item->id, '<i class="icon-trash icon-white"></i> Delete', array('class' => 'btn btn-small btn-danger', 'onclick' => "return confirm('Are you sure?')")); ?>			
				<?php endif; ?>
			    </div>
			</div>

		    </td>
		</tr>
	    <?php endforeach; ?>	
        </tbody>
    </table>

<?php else: ?>
    <p>No Stocks.</p>

<?php endif; ?>
<?php if ($auth_instance->member(50) || $auth_instance->member(100)) : ?>
    <p>
	<?php echo Html::anchor('stocks/edit', 'Add new Stock', array('class' => 'btn btn-success')); ?>
    </p>
<?php endif; ?>