<h2>Listing 
    <span class='muted'>
	<?= (isset($isAdmins) ? 'Admins' : 'Users'); ?>
    </span>
</h2>
<br>
<?php if ($users): ?>
    <table class="table table-striped">
        <thead>
    	<tr>
    	    <th>Username</th>
    	    <th>Email</th>
    	    <th>Full Name</th>
    	    <th>Group #</th>
    	    <th>&nbsp;</th>
    	</tr>
        </thead>
        <tbody>
	    <?php foreach ($users as $item): ?>		<tr>

		    <td><?php echo $item->username; ?></td>
		    <td><?php echo $item->email; ?></td>
		    <td><?php echo $item->profile->full_name; ?></td>
		    <td><?php echo $item->group; ?></td>
		    <td>
			<div class="btn-toolbar">
			    <div class="btn-group">
				<?php echo Html::anchor('users/view/' . $item->id, '<i class="icon-eye-open"></i> View', array('class' => 'btn btn-small')); ?>						
				<?php echo Html::anchor('users/edit/' . $item->id, '<i class="icon-wrench"></i> Edit', array('class' => 'btn btn-small')); ?>						
			</div>

		    </td>
		</tr>
	    <?php endforeach; ?>	</tbody>
    </table>

<?php else: ?>
    <p>No Users.</p>

<?php endif; ?><p>
    <?php echo Html::anchor('users/edit', 'Add new User', array('class' => 'btn btn-success')); ?>

</p>
