<h2>Viewing <span class='muted'>#<?php echo $user->id; ?></span></h2>

<p>
    <strong>Username:</strong>
    <?php echo $user->username; ?>
</p>
<p>
    <strong>Email:</strong>
    <?php echo $user->email; ?>
</p>
<p>
    <strong>Name:</strong>
    <?php echo $user->profile->full_name; ?>
</p>
<p>
    <strong>Phone:</strong>
    <?php echo $user->profile->phone; ?>
</p>
<p>
    <strong>Phone:</strong>
    <?php echo $user->profile->phone; ?>
</p>
<p>
    <strong>Web site:</strong>
    <?php echo $user->profile->website; ?>
</p>

<?php echo Html::anchor('users/edit/' . $user->id, 'Edit'); ?> |
<?php echo Html::anchor('users', 'Back'); ?>